apple/swift-algorithms

- Guides/Chain.md
- Guides/Chunked.md
- Guides/Combinations.md
- Guides/Cycle.md
- Guides/Indexed.md
- Guides/Partition.md
- Guides/Permutations.md
- Guides/Product.md
- Guides/RandomSampling.md
- Guides/Rotate.md
- Guides/Unique.md
This PR fixes links in the markdown files in the Guides directory, which incorrectly reference AlgorithmsTests instead of SwiftAlgorithmsTests
> Fix URLs for Tests in Guides Directory

- Guides/RandomSampling.md
Replaces usage of `randomElements` with `randomSample` in the Random Sampling guide.
> Fix method name in Random Sampling guide

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/NEW.md
This PR fix the path for contribution guidelines in PR templates.
> Fix contribution guidelines link in PR templates

- Sources/Algorithms/Chain.swift
- Tests/SwiftAlgorithmsTests/ChainTests.swift
This PR implements the `distance(from:to:)` method that was missing from `Chain`.
> Implement distance(from:to:) for Chain

- Sources/Algorithms/RandomSample.swift
`log` & `exp` functions are declared in `ucrt.corecrt.math` module on Windows.
This change makes the package buildable with SwiftPM on Windows.
> Fix build on Windows

- Sources/Algorithms/Chain.swift
- Tests/SwiftAlgorithmsTests/ChainTests.swift
`Chain`'s index offsetting logic is untested and contains a few bugs, all these assertions fail:
```swift
let chain = "abc".chained(with: "XYZ")
do {
let i = chain.index(chain.startIndex, offsetBy: 3, limitedBy: chain.startIndex)
XCTAssertNil(i)
}
do {
let i = chain.index(chain.startIndex, offsetBy: 4)
let j = chain.index(i, offsetBy: -2)
XCTAssertEqual(chain[j], "c")
}
do {
let i = chain.index(chain.startIndex, offsetBy: 3)
let j = chain.index(i, offsetBy: -1, limitedBy: i)
XCTAssertNil(j)
}
```
I've put the fixes for these in a separate commit for reference.
Another issue with the current implementation is that `chain.index(i, offsetBy: n)` (with `i` pointing into `base1`) always computes the distance from `i` to `base1.endIndex`, regardless of `n`. As a result, this code traverses the …
> Fix and improve `Chain`'s index offsetting logic

- Sources/Algorithms/Product.swift
- Tests/SwiftAlgorithmsTests/ProductTests.swift
This PR changes the way `Product2.endIndex` is represented: instead of `(base1.endIndex, base2.endIndex)`, it is now `(base1.endIndex, base2.startIndex)`.
The latter turns out to be a more natural way of representing the "past the end" index because it is exactly the index after the last valid index `(lastValidIndexOfBase1, lastValidIndexOfBase2)` according to the existing mechanism of advancing any other index of `Product2`. As a result, the methods `index(before:)`, `index(after:)`, and `distance(from:to:)` don't need any custom logic to deal with `endIndex`.
`endIndex` wasn't handled correctly everywhere so this also ends up fixing bugs in `index(before:)` and `distance(from:to:)`.
> Fix `Product2`'s indexing logic

- .xcodesamplecode.plist
The downside to doing this is that it makes the files more inconvenient to edit, since Xcode doesn't let you toggle out of the rendered view easily, but I think it makes sense on the premise that these are read much more often than edited. I have this flag set in Swift Numerics for this reason.
> Add the magic plist file to make xcode render the markdown guides.

- Package.swift
- Sources/Algorithms/RandomSample.swift
This drops the canImport darwin/glibc/etc dance, which is ugly, and lets us use `root` instead of `exp(log(x)/k)`, which is more accurate in some cases (but mainly is just nicer to read).
The downside is that this introduces a dependency for Algorithms, where previously it had none. I think that Numerics is an OK thing to depend on (especially for these functions, which are available from 0.0.1), but it _is_ a _massive increase_ in the number of dependencies that the package has, and we should give that some thought.
> Use Swift Numerics for elementary functions

- Sources/Algorithms/Partition.swift
- Tests/SwiftAlgorithmsTests/PartitionTests.swift
Function `stablePartition(subrange:by:)` in `Partition` should not using the collection count which will cause bound error, but using subrange count.
> Fix stablePartition(subrange:by:) using subrange count instead of entire collection count.

- Guides/Chain.md
- Guides/Combinations.md
- Guides/Cycle.md
- Guides/Indexed.md
- Guides/Permutations.md
- Sources/Algorithms/Chain.swift
- Sources/Algorithms/Combinations.swift
- Sources/Algorithms/Cycle.swift
- Sources/Algorithms/Indexed.swift
- Sources/Algorithms/Permutations.swift
- Tests/SwiftAlgorithmsTests/ChainTests.swift
- Tests/SwiftAlgorithmsTests/ChunkedTests.swift
- Tests/SwiftAlgorithmsTests/CombinationsTests.swift
- Tests/SwiftAlgorithmsTests/CycleTests.swift
- Tests/SwiftAlgorithmsTests/IndexedTests.swift
- Tests/SwiftAlgorithmsTests/PermutationsTests.swift
- Tests/SwiftAlgorithmsTests/TestUtilities.swift
This adds overloads to `LazySequenceProtocol` of existing lazy-by-default sequence algorithms, for the sole purpose of keeping lazy chains lazy when one of these methods is called.
`uniqued` is left out of this because it (currently) isn't lazy to begin with. A `LazySequenceProtocol` overload will only make sense once we have a `Uniqued` sequence that produces unique elements on demand.
Two unresolved questions:
- Do we want all of these overloads? I've added them for all algorithms that have a `self` and return a new sequence/collection, but that might be too lenient. (Is there a guideline for this somewhere?)
- Should the guides mention these overloads, given that they don't add any actual functionality? The Chunked guide mentions them, but then again `lazy.chunked` and `.chunked.lazy` …
> Add conditional LazySequenceProtocol conformance

- Guides/Chain.md
- README.md
- Sources/Algorithms/Chain.swift
- Tests/SwiftAlgorithmsTests/ChainTests.swift
This follows a forum discussion about the `chained(with:)` name. The old names are preserved as deprecated symbols.
The new version of `chain` looks like this:
```swift
func chain<S1, S2>(_ s1: S1, _ s2: S2) -> Chain2<S1, S2>
```
Updated the symbol documentation, guide, and README.
Updated existing tests to use the new name.
This deprecates the `chained(with:)` method and the `Chain2` type.
> Rename `chained(with:)` to `chain(_:_:)`

- Tests/SwiftAlgorithmsTests/ChainTests.swift
- Tests/SwiftAlgorithmsTests/ProductTests.swift
- Tests/SwiftAlgorithmsTests/TestUtilities.swift
This is a stab at making the index tests from `ChainTests` available to other collections as well (for now just `chain` and `product`). `validateIndexTraversals` validates a collection by taking an array of its indices as the source of truth, and verifying that all index operations (with just about any combination of arguments possible) are consistent with these indices.
`validateIndexTraversals` doesn't just use `c.indices + [c.endIndex]` as the indices to test against because that might not catch a bug in the implementation of `indices` itself (or e.g. `index(after:)` or `Index.==`). Having to provide an array of indices that are known to be correct prevents these kinds of bugs from slipping through. As an example, the index array of a `Chain2` instance is computed like this:
```swift …
```
> General index consistency tests

- Guides/Trim.md
- README.md
- Sources/Algorithms/Trim.swift
- Tests/SwiftAlgorithmsTests/TrimTests.swift
Adds a '.trimming' method to BidirectionalCollection, returning a slice with matching elements removed from the start and end.
```swift
extension BidirectionalCollection {
/// Returns a `SubSequence` formed by discarding all elements at the start and end of the Collection
/// which satisfy the given predicate.
///
/// e.g. `[2, 10, 11, 15, 20, 21, 100].trimmimg(where: { $0.isMultiple(of: 2) })` == `[11, 15, 20, 21]`
///
/// - parameters:
///    - predicate:  A closure which determines if the element should be omitted from the resulting slice.
///
@inlinable
public func trimming(where predicate: (Element) throws -> Bool) rethrows -> SubSequence
}
```
No existing guides need updating AFAIK. I haven't written a guide for this feature: is it necessary for every API to include this parallel …
> Add BidirectionalCollection.trimming

- Sources/Algorithms/Product.swift
This PR gets rid of any unnecessary computations in `Product2.distance(from:to:)`. In particular, it now only does a single pass over `base2` in the worst case (instead of 3), and for non-random-access collections it no longer does more index calculations than the default implementation of `distance(from:to:)`.
> Improve performance of Product2.distance(from:to:)

- Guides/Intersperse.md
- Sources/Algorithms/Intersperse.swift
- Tests/SwiftAlgorithmsTests/IntersperseTests.swift
- Tests/SwiftAlgorithmsTests/TestUtilities.swift
This addition allows the caller to insert values between each element of a sequence. In this way you could have a string and insert a hyphen between each character or you could have an array of SwiftUI views and insert a separator view between each.
To achieve this, a new sequence type called Intersperse is added to the library. It also conforms to Collection and BidirectionalCollection when the base sequence conforms to those respective protocols.
For ease of use, a new method is added to sequence to allow the interspersing of the separator element:
```swift
extension Sequence {
func interspersed(with separator: Element) -> Intersperse<Self>
}
```
It is crucial that the separator is only inserted between elements, so before returning the separator element, a lookup is performed on the …
> Add interspersed(with:)

- Sources/Algorithms/SlidingWindows.swift
- Tests/SwiftAlgorithmsTests/SlidingWindowsTests.swift
`index(_:offsetBy:)`, `index(_:offsetBy:limitedBy:)`, and `distance(from:to:)` for `SlidingWindows`.
The `base.endIndex..<base.endIndex` representation of `endIndex` made this a bit tricky, because neither of the bounds is a logical successor of the index before it. The `offsetForward`/`offsetBackward` dance alleviates this somewhat by ensuring that the limit is always on the correct side of `i` and never equal to it, removing some of the edge cases.
> Add random-access methods to SlidingWindows

- Guides/Indexed.md
- Guides/Intersperse.md
- Guides/SlidingWindows.md
- Sources/Algorithms/Indexed.swift
- Sources/Algorithms/Intersperse.swift
- Sources/Algorithms/SlidingWindows.swift
- Tests/SwiftAlgorithmsTests/ChunkedTests.swift
- Tests/SwiftAlgorithmsTests/CombinationsTests.swift
- Tests/SwiftAlgorithmsTests/CycleTests.swift
- Tests/SwiftAlgorithmsTests/IndexedTests.swift
- Tests/SwiftAlgorithmsTests/IntersperseTests.swift
- Tests/SwiftAlgorithmsTests/PermutationsTests.swift
- Tests/SwiftAlgorithmsTests/SlidingWindowsTests.swift
- Tests/SwiftAlgorithmsTests/TestUtilities.swift
This fixes an omission in `Intersperse` where it doesn't currently conform to `LazySequenceProtocol` when the base sequence also conforms to `LazySequenceProtocol`.
> Add conformances to LazySequenceProtocol and LazyCollectionProtocol

- Guides/Stride.md
- Sources/Algorithms/Stride.swift
- Tests/SwiftAlgorithmsTests/StrideTests.swift
Many thanks to @timvermeulen for continued help!
A type that steps over a collection’s elements by the specified amount.
This is available through the `striding(by:)` method on any `Collection`.
```swift
(0...10).striding(by: 2) // == [0, 2, 4, 6, 8, 10]
```
If the stride is larger than the collection count, the resulting wrapper only contains the 
first element.
The stride amount must be a positive value.
The `striding(by:)` method is declared as a `Collection` extension, and returns a 
`Stride` type:
```swift
extension Collection {
public func striding(by step: Int) -> Stride<Self>
}
```
A custom `Index` type is defined so that it's not possible to get confused when trying 
to access an index of the stride collection.
```swift
[0, 1, 2, 3, 4].striding(by: 2)[1] // == 1
[0, 1, 2, 3, …
```
> Add Stride for Collection

- Sources/Algorithms/Combinations.swift
- Sources/Algorithms/Rotate.swift
- Sources/Algorithms/Trim.swift
This PR contains a few minor changes to comments, namely:
- `Combinations.swift` contained an invalid source code example
- `Rotate.swift` was missing the definition of *n* (for (O(*n*))
- `Trim.swift`s formatting diverged from the rest of the project 
- Comments did not break on or before line # 80
- Replaced the delimiter names `parameters` and `complexity` with `Parameters` and `Complexity` respectively
- Replaced \`O(n)\` and \`n\` with O(\*n\*) and \*n\* respectively
> Cleaning up some comments

- Sources/Algorithms/Chunked.swift
Unify `chunked(by:)` and `chunked(on:)` by:
- forwarding the eager versions to a new internal `chunked(on:by:)`, and
- having `LazyChunked` store both a projection function and a predicate.
The status quo of `chunked(on:)` calling `chunked(by: { f($0) == f($1) })` causes more calls to the projection function than necessary, specifically by repeatedly calling it with the first element of the chunk. Unifying `chunked(by:)` and `chunked(on:)` allows this projected value to be stored and reused.
This PR also slightly improves `endOfChunk(startingAt:)` by moving the `endIndex` check to `index(after:)` (at the only point where it can ever be hit). This change, together with changing the `endIndex` representation to have no upper bound, has the pleasant consequence that …
> Unify chunked(by:) and chunked(on:)

- Guides/Combinations.md
- README.md
- Sources/Algorithms/Combinations.swift
- Tests/SwiftAlgorithmsTests/CombinationsTests.swift
This addition adds the ability to easily get combinations of a range of sizes, instead of the previous behavior of a single, fixed size, `k`.
The `combinations(ofCount:)` function that takes a `RangeExpression` is added in an extension of `Collection`.
```swift
extension Collection {
public func combinations<R: RangeExpression>(
ofCount kRange: R
) -> Combinations<Self> where R.Bound == Int {
return Combinations(self, kRange: kRange)
}
}
```
If the upper bound of the range exceeds the length of the collection, no such combinations of those sizes will be returned, effectively clamping the range to `0...n` where `n` is the length of the collection. The behavior of negative numbers also remains unchanged (asserting).
This also updates the implementation of the existing …
> All combinations

- Guides/Chunked.md
- README.md
- Sources/Algorithms/Chunked.swift
- Tests/SwiftAlgorithmsTests/ChunkedTests.swift
This just adds the `chunks(of:)` to chunk a collection into subsequences of a given size. 
As suggested by @bjhomer [here](https://forums.swift.org/t/pull-in-chunks-ofsize-from-separate-proposal/42575) this is just moving a long time opened [evolution proposal](https://forums.swift.org/t/pull-in-chunks-ofsize-from-separate-proposal/42575) to this package. So let me know what you think =] 
cc @natecook1000 @kylemacomber
> [Chunked] Add `chunks(of:)` variant that divides a collection in chunks of a given size

- README.md
Adds `slidingWindows(ofCount:)` and `striding(by:)` to README.md
> Update README.md to add slidingWindows(ofCount:) and striding(by:)

- Sources/Algorithms/Combinations.swift
- Sources/Algorithms/Permutations.swift
I think that makes sense to `precondition` instead of `assert` in those cases :) 
It also aligns with we currently have for others like `SlidingWindows`. 
cc @natecook1000 @kylemacomber 
Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.
> [NFC] Using precondition instead of assert in calls that do not allow negative values

- Guides/Permutations.md
- Sources/Algorithms/Permutations.swift
- Tests/SwiftAlgorithmsTests/PermutationsTests.swift
This addition adds the ability to easily get permutations of a range of sizes, instead of the previous behavior of a single, fixed size, `k`, like https://github.com/apple/swift-algorithms/pull/51 did for `Combinations`.
The `permutations(ofCount:)` function that takes a `RangeExpression` is added in an extension of `Collection`.
```swift
extension Collection {
public func permutations<R: RangeExpression>(
ofCount kRange: R
) -> Permutations<Self> where R.Bound == Int {
return Permutations(self, kRange: kRange)
}
}
```
If the upper bound of the range exceeds the length of the collection, no such permutations of those sizes will be returned, effectively clamping the range to `0...n` where `n` is the length of the collection.
The name `permutations(ofCount:)` is the same as the original, …
> All permutations

- Sources/Algorithms/RandomSample.swift
- Tests/SwiftAlgorithmsTests/RandomSampleTests.swift
Fix https://github.com/apple/swift-algorithms/issues/69 .
I changed the random ranges from `[0, 1)` to `(0, 1]` .
`w` must not be `0` so fixed `nextW` too. (in `log(1 - w)`, `log(1)` is `0` so zero division happens.)
> Fix RandomSample crash when 0 was out from random.

- Sources/Algorithms/Product.swift
This PR adds implementations of `index(_:offsetBy:)` and `index(_:offsetBy:limitedBy:)` to the `Product2` collection. There are ways to further reduce the amount of indices traversed, but this should perform well enough.
LIke `Chain2`, `Product2`'s index offsetting behavior will now unfortunately perform slightly worse for non-random-access collections in specific scenarios, but there's not much we can do about that.
> Index offsetting for Product2

- Sources/Algorithms/Rotate.swift
- Tests/SwiftAlgorithmsTests/RotateTests.swift
- Adds specific unit tests for the documented examples of the `rotate` functions. It’s good to specifically test the examples in the documentation. After all, those are the cases that are absolutely expected to work.
- Adds unit tests for `_reverse(subrange:until:)` and `reverse(subrange:)`
- Within documentation and implementation of `_reverse(subrange:until:)`, use `lower` and `upper` instead of `f` and `l`. `l` could easily be misinterpreted as `lower`, `left`, or `limit`. Using `lower` and `upper` avoids this ambiguity.
- Use consistent variable names `lower` and `upper` instead of `lo`, and `hi`, respectively, in `reverse(subrange:)`. This is more consistent with `lowerBound` and `upperBound`.
> Add additional tests to rotate functions, clarify variable names

- Sources/Algorithms/Chain.swift
- Sources/Algorithms/Chunked.swift
- Sources/Algorithms/Cycle.swift
- Sources/Algorithms/Intersperse.swift
- Sources/Algorithms/Permutations.swift
- Sources/Algorithms/Product.swift
- Sources/Algorithms/Stride.swift
- Sources/Algorithms/Suffix.swift
- Sources/Algorithms/Windows.swift
Tackle items `Audit inlinability annotations throughout` of #80 
* Make public methods and properties inlinable
Note: I didn't touch `sortedPrefix` file to avoid conflicts with renaming PR in progress =] 
cc @natecook1000 @kylemacomber @timvermeulen 
Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.
> [0.0.3] Audit public functions and properties that could be inlinable

- README.md
The link in README.md was still referencing SlidingWindows.md after it was renamed to Windows.md.
> Correct link to Windows.md in README.me

- Sources/Algorithms/Chunked.swift
- Sources/Algorithms/Suffix.swift
- Sources/Algorithms/Trim.swift
- Tests/SwiftAlgorithmsTests/SuffixTests.swift
Internally adds the `endOfPrefix(while:)` method to `Collection` and the `startOfSuffix(while:)` method to `BidirectionalCollection`.
These methods return the same values as `prefix(while: predicate).endIndex` and `suffix(while: predicate).startIndex`, respectively. We're adding them as internal methods for now because we're already using this functionality in several places throughout the package, but it's unclear whether these are the names we want to stick with.
> Internally add Collection.endOfPrefix(while:) and BidirectionalCollection.startOfSuffix(while:)

- Tests/SwiftAlgorithmsTests/TestUtilities.swift
Implements improvement suggested @timvermeulen in #100
Improves the `XCTAssertEqualSequences` function to log when two elements in a sequence are not equivalent or when one of the sequences is shorter than the other.
I implemented it such that as soon as it finds to unequal elements between the sequences, it'll fail and stop without looking at the remaining elements. We could try to make it more sophisticated if that's the goal.
I'm not sure how to test it, since it's a test helper utility. As it stands, `XCTAssertEqualSequences` was not being tested. The test suite, which heavily depends on the function still passes after the changes but that doesn't exercise the function in the failure cases or its output. I experimented with that by changing some tests to make them fail and it seemed …
> Improve XCTAssertEqualSequences to log difference

- Sources/Algorithms/Chain.swift
- Sources/Algorithms/Chunked.swift
- Sources/Algorithms/Combinations.swift
- Sources/Algorithms/Cycle.swift
- Sources/Algorithms/Indexed.swift
- Sources/Algorithms/Intersperse.swift
- Sources/Algorithms/LazySplit.swift
- Sources/Algorithms/Partition.swift
- Sources/Algorithms/Permutations.swift
- Sources/Algorithms/Product.swift
- Sources/Algorithms/Rotate.swift
- Sources/Algorithms/Stride.swift
- Sources/Algorithms/Suffix.swift
- Sources/Algorithms/Windows.swift
#92 introduced quite a serious performance regression by refactoring inlinable code in to a helper function which was only _usable_ from inlined code, but not itself inlinable. The first commit corrects this.
Upon further inspection, I noticed a pattern - that _all_ internal functions seemed to only be `@usableFromInline` and not `@inlinable`, whereas their public siblings were all `@inlinable`. Inlining is critical for exactly this kind of code - lazy wrappers and collections and so on, and especially when they are generic. For instance, how is the client's instance of the compiler supposed to be able to optimise `Chain`, when the implementation of `offsetForward` is hidden from it?
So the second commit inlines basically everything that was previously `@usableFromInline`.
Additionally, I …
> Inline all the things! 🎨

- Guides/Permutations.md
- README.md
- Sources/Algorithms/Permutations.swift
- Tests/SwiftAlgorithmsTests/UniquePermutationsTests.swift
Adds methods for generating the unique permutations of a sequence, as distinct from the position-based permutations generated by `permutations()`.
Includes new `uniquePermutations(ofCount:)` methods (for both single counts and range expressions) and the wrapping `UniquePermutations` type. The method requires that a collection's elements be hashable so that uniqueness can be determined in a pre-processing pass:
```swift
extension Collection where Element: Hashable {
/// Returns a sequence of the unique permutations of this collection.
///
/// Use this method to iterate over the unique permutations of a sequence
/// with repeating elements. This example prints every permutation of an
/// array of numbers:
///
///     let numbers = [1, 2, 2]
///     for perm in numbers.uniquePermutations() { …
```
> Add uniquePermutations as wrapper for nextPermutation

- Sources/Algorithms/Reductions.swift
As mentioned by @karwa in #109, functions should be marked as `@inlinable`. Due to timing of the two pull requests, the `reductions` addition hadn't taken this change into account. This change resolves that by making all the internal functions `@inlinable`.
> Inline all the reductions things!

- Guides/Reductions.md
- Sources/Algorithms/Reductions.swift
- Tests/SwiftAlgorithmsTests/ReductionsTests.swift
> Remove the inout on reductions(into:_:) to be consistent with the stdlib reduce(into:_)

- Guides/Compacted.md
- README.md
- Sources/Algorithms/Compacted.swift
- Tests/SwiftAlgorithmsTests/CompactedTests.swift
- Tests/SwiftAlgorithmsTests/TestUtilities.swift
Fixes #107 
From the sketch from @kylemacomber on the issue, this just complement the implementation adding the tests and docs.
Let me know what you think =]
cc @kylemacomber @natecook1000 @timvermeulen 
Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.
> [Compacted] Adding `compacted()` method to remove all nils in a sequence or collection

- Sources/Algorithms/Chain.swift
- Sources/Algorithms/Chunked.swift
- Sources/Algorithms/Combinations.swift
- Sources/Algorithms/Cycle.swift
- Sources/Algorithms/Indexed.swift
- Sources/Algorithms/Permutations.swift
- Sources/Algorithms/Product.swift
- Sources/Algorithms/Windows.swift
Making all collection/sequence wrappers base properties internal 
Fixes #84 
cc @natecook1000 @timvermeulen
> [Source Break] Making all collection/sequence wrappers base properties internal 

- Sources/Algorithms/Chunked.swift
- Tests/SwiftAlgorithmsTests/ChunkedTests.swift
- Tests/SwiftAlgorithmsTests/TestUtilities.swift
After the Nate's comments about hashable correctness in the last PR I note that we have miss that on `ChunkedByCount`. 
This just adjust to take the count in hash computation. 
cc @natecook1000 @timvermeulen
> [tests] Ensure correct implementation of hash computation for ChunkedByCount

- Sources/Algorithms/Chain.swift
Adopts the index offsetting structure of `Product2` to ensure that `offsetForward` and `offsetBackward` are only ever called with a `limit` on the correct side of the index, reducing the number of cases that need to be handled.
> Simplify `Chain`'s index offsetting

- Guides/Unique.md
- Sources/Algorithms/Unique.swift
- Tests/SwiftAlgorithmsTests/UniqueTests.swift
Adds the `Uniqued` sequence that lazily produces the unique elements of a sequence. `uniqued()` and `lazy.uniqued(on:)` now return a `Uniqued` instance, the eager `uniqued(on:)` still produces an array.
> Make `uniqued()` lazy by default

- Guides/Cycle.md
- Sources/Algorithms/Cycle.swift
- Sources/Algorithms/Product.swift
- Tests/SwiftAlgorithmsTests/CycleTests.swift
This PR aims to fix #99. I have also split up some relevant tests into separate methods for empty collections and changed some tests for `FiniteCycle`. I have also added tuple labels to `Product2` when using the `Iterator.next()` method and also in the `subscript` method. This is a cosmetic improvement, but I felt it may read better.
> Add new `FiniteCycle` type as the return type of `Collection.cycled(times:)`

- Guides/Reductions.md
- Guides/Trim.md
Just few typos caught by [vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker) VSCode extension :)
> [NFC] Fixing typos on guides

- Guides/Compacted.md
- Guides/Cycle.md
- README.md
> Light revisions to guides

- Sources/Algorithms/Product.swift
> Fix `Product2` associated type inference error in release build

- README.md
I think this is what the `partitionIndex` method needs to be described as per #131, please let me know any feedback 😊.
> Add new heading and description for partitionIndex 🤷‍♂️.

- CHANGELOG.md
- Guides/AdjacentPairs.md
- README.md
- Sources/Algorithms/AdjacentPairs.swift
- Tests/SwiftAlgorithmsTests/AdjacentPairsTests.swift
Implements an `adjacentPairs` algorithm on Sequence, per forum discussion: https://forums.swift.org/t/add-an-adjacentpairs-algorithm-to-sequence/14817.
Lazily iterates over tuples of adjacent elements.
This operation is available for any sequence by calling the `adjacentPairs()` method.
```swift
let numbers = (1...5)
let pairs = numbers.adjacentPairs()
// Array(pairs) == [(1, 2), (2, 3), (3, 4), (4, 5)]
```
The `adjacentPairs()` method is declared as a `Sequence` extension returning `AdjacentPairs`.
```swift
extension Sequence {
public func adjacentPairs() -> AdjacentPairs<Self>
}
```
The resulting `AdjacentPairs` type is a sequence, with conditional conformance to `Collection`, `BidirectionalCollection`, and `RandomAccessCollection` when the underlying sequence conforms.
The spelling …
> Introduce `adjacentPairs`

- Sources/Algorithms/AdjacentPairs.swift
- Tests/SwiftAlgorithmsTests/AdjacentPairsTests.swift
Update the `AdjacentPairs` implementation based on code review in #119.
> Update AdjacentPairs implementations and tests

- Sources/Algorithms/MinMax.swift
- Tests/SwiftAlgorithmsTests/MinMaxTests.swift
This removes the `#if`s to land on a single implementation for `minAndMax()` and adds a couple of additional tests.
> Minor revisions to `minAndMax()`

- Guides/Chunked.md
- Sources/Algorithms/Chunked.swift
- Tests/SwiftAlgorithmsTests/ChunkedTests.swift
This PR changes the result of calling `chunked(on:)` to `[(Subject, SubSequence)]`, and adds a new collection type as the result of `lazy.chunked(on:)` with a matching element type. Including the projected `Subject` is often useful when chunking on a projected value like this.
The new versions of `chunked(on:)` looks like this:
```swift
extension Collection {
public func chunked<Subject: Equatable>(
on projection: (Element) throws -> Subject
) rethrows -> [(Subject, SubSequence)]
}
extension LazyCollectionProtocol {
public func chunked<Subject: Equatable>(
on projection: (Element) throws -> Subject
) rethrows -> ChunkedOn<Self, Subject>
}
```
I've also changed the name `Chunked` to be `ChunkedBy`, since this PR introduces `ChunkedOn`.
> Make chunked(on:) include subject value in Element type

- Guides/Trim.md
- Sources/Algorithms/Trim.swift
- Tests/SwiftAlgorithmsTests/TrimTests.swift
Closes #101 
`trimming(while:)` is split in two methods `trimmingPrefix(while:)` which is available to all `Collection`s and `trimmingSuffix(while:)` available only to `BidirectionalCollection`s.
This also adds a mutable variant of each `trim` method where `SubSequence == Self`.
```swift
func trimmingSuffix(
while predicate: (Element) throws -> Bool
) rethrows -> SubSequence {
let end = try self[startIndex...].startOfSuffix(while: predicate)
return self[startIndex..<end]
}
func trimmingPrefix(
while predicate: (Element) throws -> Bool
) rethrows -> SubSequence {
let start = try endOfPrefix(while: predicate)
return self[start..<endIndex]
}
func trimming(
while predicate: (Element) throws -> Bool
) rethrows -> SubSequence {
return try trimmingPrefix(while: predicate).trimmingSuffix(while: …
```
> Add `trimmingSuffix`, `trimmingPrefix` and mutating variants

- Guides/Joined.md
- Sources/Algorithms/EitherSequence.swift
- Sources/Algorithms/FlattenCollection.swift
- Sources/Algorithms/Intersperse.swift
- Sources/Algorithms/Joined.swift
- Tests/SwiftAlgorithmsTests/IntersperseTests.swift
- Tests/SwiftAlgorithmsTests/JoinedTests.swift
This PR adds 4 ways of joining sequences of sequences with a separator, two of which let you base the separator on the sequences right before and after it:
```swift
extension Sequence where Element: Sequence {
public func joined(by separator: Element.Element)
-> JoinedBySequence<Self, CollectionOfOne<Element.Element>>
public func joined<Separator>(
by separator: Separator
) -> JoinedBySequence<Self, Separator>
where Separator: Collection, Separator.Element == Element.Element
public func joined(
by separator: (Element, Element) throws -> Element.Element
) rethrows -> [Element.Element]
public func joined<Separator>(
by separator: (Element, Element) throws -> Separator
) rethrows -> [Element.Element]
where Separator: Sequence, Separator.Element == Element.Element
}
```
Also adds the …
> Add `joined(by:)`

- Sources/Algorithms/Stride.swift
Improve compile times for consumers using older versions of Xcode/swift. This change significantly improves compile times when using Swift 5.3.2. More details & benchmarks in #146 
*Edit* - Pushed a small change to the wording of the comment
> Remove compilation bottleneck for Swift 5.3.2 builds

- Sources/Algorithms/Compacted.swift
There was two spaces in the middle of a sentence in the inline documentation for `compacted()`
> Remove extraneous space in inline documentation

- Sources/Algorithms/Chunked.swift
- Tests/SwiftAlgorithmsTests/ChunkedTests.swift
Fixes #161.
```swift
[a, b, c, d].chunked(by: { print($0, $1); return true })
// previous behavior: (a, b), (a, c), (a, d)
// correct behavior:  (a, b), (b, c), (c, d)
```
> Ensure `chunked(by:)` always compares consecutive elements

- Sources/Algorithms/MinMax.swift
Previously, in `_minImplementation(count:sortedBy:)`, when finding a new, smaller element, we were calculating the insertion index on the full-sized collection, subsequently removing the last element, then inserting the new element at that insertion index. This has a couple small problems:
1. We were calling `partitioningIndex(where:)` on a larger collection than necessary. By removing the last element first (which doesn’t need to be compared against again), we make the collection slightly smaller, resulting in fewer comparisons. For simple comparisons (like `Int`s), this isn’t a big deal, but if the comparison is more expensive (like with a custom struct with multiple properties), this can make a slight difference.
2. The insertion index that we found could theoretically be invalidated …
> `min(count:…)` implementation: Remove the last element before determining the insertion index

- Sources/Algorithms/Partition.swift
- Tests/SwiftAlgorithmsTests/PartitionTests.swift
Resolves https://github.com/apple/swift-algorithms/issues/170
> Clarify `endIndex` behavior of `partitioningIndex(where:)` in documentation (Resolves #170)

- Sources/Algorithms/Chunked.swift
- Replace “past” with “passed”
- Add missing spaces before parenthesis
- Add back ticks around code references
- Add missing comma
> Update comments in Chunked.swift

- Sources/Algorithms/MinMax.swift
The variable smallestThree should really be named largestThree. Looks like this was originally a copy paste error from the min documentation.
I noticed this error in the code section of the docs for max. This change only affects documentation and does not affect any actual code.
> Corrects variable name in max functions to better reflect usage

- Package.swift
All this does is add the `.git` suffix to the package URL for `swift-numerics`. Why do this?
- Consistency. A majority of the other Apple-published Swift ecosystem packages (`swift-logging`, `swift-crypto`, `swift-certificates`, `swift-asn1`, `swift-collections`, `swift-docc`, `swift-nio`, `swift-argument-parser`, `swift-atomics`, and so on) use the `.git`-suffixed form, if not exclusively, then more often than not.
- It makes a difference. If, for example, the same dependency is specified more than once in a given dependency graph and the use of the suffix is inconsistent, SwiftPM does take notice (although the message is only shown when `-v` is in use):
```
info: 'swift-algorithms': dependency on 'swift-numerics' is represented by similar locations …
```
> Specify dependency URL in consistent fashion

- Guides/AdjacentPairs.md
- Guides/Combinations.md
Pulled this unrelated change out of #197
cc @stephentyrone
> [Docs] Add link and remove redundant doc line

- Guides/Trim.md
- Sources/Algorithms/Documentation.docc/Trimming.md
- Sources/Algorithms/Suffix.swift
- Sources/Algorithms/Trim.swift
- Tests/SwiftAlgorithmsTests/SuffixTests.swift
This supplants #186, making the `endOfPrefix(while:)` and `startOfSuffix(while:)` methods public.
> Make trimming helper methods public

- Sources/Algorithms/Combinations.swift
- Tests/SwiftAlgorithmsTests/CombinationsTests.swift
Not doing this makes it needlessly costly to create an Array of the results.
It's a reasonable incremental improvement until you get around to #219, which would handle this automatically.
> CombinationsSequence: underestimatedCount == count

- Sources/Algorithms/RandomSample.swift
These annotations produce warnings when compiling without library evolution using Swift ≥5.10.
Replace them by private import when compiling using Swift ≥5.11.
Mirrors apple/swift-syntax#2429
> Remove `@_implementationOnly` annotations

- Sources/Algorithms/Partition.swift
As currently written, the summary for `partitioned(by:)` heavily implies the return value is `(trueValues, falseValues)`. In fact, it’s the opposite. I rephrased this summary to clarify that (1) the order is `(falseValues, trueValues)` and (2) the elements of the two returned arrays are in the order they were in the original sequence/collection.
- (N/A) I've added at least one test that validates that my change is working, if appropriate
> Clarify the docs for `partitioned(by:)`

- Package.swift
This updates the Swift Algorithms package to have a base of Swift 5.7, which is the earliest version supported by these packages.
> Update project to depend on Swift 5.7

- CHANGELOG.md
Updated changelog. The `ends(with:)` addition needs to wait for the 1.3.0 release, which will be scheduled soon.
> Prepare for 1.2.1 release
